### PR TITLE
Added delhi scraper

### PR DESCRIPTION
**Pull request by pystardust**

### CODE REVIEW

**Comment by pystardust** [comment]
We could convert these rec files back to json as needed.
Data parsing is much easier in recfiles than json in the shell

**Review by itzjustalan — APPROVED** [review]

**Review by gi-yt — COMMENTED** [review]
Nice. But Just pipe the out into less. It Just spits it into the screen.

**Comment by pystardust** [comment]
@gi-yt this is just the scraper, we would call this function from another script

**Comment by gi-yt** [comment]
oh ok @pystardust i misunderstood sorry.

**Pull request merged**
